### ISSUE TITLE
Navbar toggle button behaviour Alpha 5

### ISSUE THREAD

**Issue by typeplus** [holger1411/understrap#105]
Is it normal for the Navbar Hamburger (was a span) to not have the `cursor:pointer;` attribute anymore? it seems to not bother and inherits the user agent setting of the browser which is `cursor:default;`

Using version of Understrap 0.4.9 with child 0.1.5.

Thanks for reading!

**Comment by holger1411** [comment]
Hi!
The 4 Alpha 5 Hamburger icon is now a `type="button"`
And `cursor: pointer;` is applied to `<button type="button">` elements.

**Comment by typeplus** [comment]
Thanks for your reply Holger. I know this is a stupid little issue and its on the bootstrap guys but it only appears to work for me if I give the toggler a `role="button"` ie;

`<button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target=".exCollapsingNavbar" aria-controls="exCollapsingNavbar" aria-expanded="false" aria-label="Toggle navigation" role="button">☰ </button>`

I am a pretty weak coder, but looking at the [official bs4 page](https://v4-alpha.getbootstrap.com/components/navbar/)  it appears the same. So its either me doing something wrong or its a strange choice to have `cursor:default;`

Is that right or am i off the mark as usual?

**Comment by holger1411** [comment]
Hi again!
Just to understand you request the right way:
Do you have a cursor:default but need a cursor:pointer
or the other way around?

The BS4 guys use cursor:pointer; for the hamburg icon button and you should see the cursor changing on hover. If not something is wrong...

**Comment by typeplus** [comment]
Hi Holger,

Yes thats right. The behaviour for the Hamburger on hover should be cursor:pointer; however it is not and it is rendered with a gray border and gray background image in addition to the hamburger icon itself.

This is a default install of Understrap 0.50 (i have not run npm install or gulp-copy assets but after capturing this I did that and it was the same);

![understrap_issue](https://cloud.githubusercontent.com/assets/20927976/19914355/e960494e-a0f9-11e6-97a4-5a30250d6e01.gif)

I have tried it on Safari, Moz, IE, Edge and Chrome and its the same thing.

This seems to fixe the issue;

```
<!-- .navbar-toggle is used as the toggle for collapsed navbar content -->
  <button class="navbar-toggler float-xs-right hidden-sm-up collapsed" data-toggle="collapse" 
    data-target=".exCollapsingNavbar" type="button" aria-controls="exCollapsingNavbar" 
      aria-expanded="false" aria-label="Toggle navigation" role="button">
</button>

```
Hey it wouldn't be the first time I completely stuffed up and got it wrong! but this is a default install. Minor issue I know!

**Comment by holger1411** [comment]
Strange thing...could you see the same behavior on our demo site:
https://understrap.com/understrap/
?

**Comment by typeplus** [comment]
Doesnt happen on that site mate, it does happen on the Bootstrap official Alpha 5 page though. Is this something that npm install and gulp copy-assets would be causing due to their sources?

**Comment by holger1411** [comment]
Ah, now I´ve got it...Don´t know if it is a BS4 bug or if it something behinde this decision.
I upgraded the demo site from BS4 Alpha 4 to Alpha 5, adjusted the navbar markup to the new BS4 markup BUT add role="button", too. See https://github.com/holger1411/understrap/commit/321bc65369f677b6fb6a6f59afcee6682d01b43f

Looks okay for now.

**Comment by typeplus** [comment]
Thanks mate, appreciate it! 👍

**Comment by Thomas-A-Reinert** [comment]
Sorry for jumping on the bandwagon after the commit. But this is not how HTML5 and ARIA-rules in general are handling it with HTML5. The role="button" attribute may solve the problem visually but it´s not the intended HTML5/ARIA-way. So just expect the Bootstrap4 solution as "intended".

Button elements do NOT need a role="button" attribute just as navs don´t need a role="navigation" anymore. But you MAY add a type="button" as well as type="navigation" as a fallback for older browsers that do not support HTML5.

The no-pointer-problem should be adressed via CSS as it´s just a visual concern for the non-visually impaired. The visually impaired will never ever have a problem with that ;)

Referring to:
- https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/button/button.html
- https://webaccessibility.withgoogle.com/unit?unit=6&lesson=9
- http://stackoverflow.com/questions/14180785/html5-nav-element-vs-role-navigation
- Für Dich Holger: Ersetz keine grundlegenden Rollen eines HTML5-Elements mit Aria Landmarks! http://www.barrierefreies-webdesign.de/knowhow/landmark-roles/
Allerdings führt das in manchen Fällen wohl immer noch zu Problemen, siehe: http://www.hellbusch.de/author/jan-eric-hellbusch/

@typeplus never rely on accessibility-markup the visual way ;) Rule of thumb: Use CSS to style it for the non-visually impaired. And: Use a tool like (amongst others) http://wave.webaim.org/ to check your accessibility-markup!

The solution for your problem is simple though. Just add:
```
button {
  cursor: pointer;
}
```
at the end of understrap.scss. Will commit that later too.

**Comment by typeplus** [comment]
@Thomas-A-Reinert thanks for the detailed post! Yes its an easy fix of `cursor:pointer;` I was just concerned why the BS guys would change it and whether it reflected some new direction. They had in their scss > css;

```
button,
[type="button"],
[type="reset"],
[type="submit"] {
  cursor: pointer; }
```

But in the latest Alpha its been removed. I am pretty clearly not that smart when it comes to coding so I hesitate to bring issues up as its most likely my fault!

Thankyou kindly for the explanation 👍

**Comment by Thomas-A-Reinert** [comment]
Yo, no problem ;)

The above mentioned code is A LOT better than mine (which covers not all cases but yours) and will fix even more cases. I´ll update it immediately.

And I´ll even try to convince bs4 ppl to adapt it into their core. Later. After some hours of sleep ;)

No need for excuses though. We (coders) are able to explain our ways of coding if requested. While you - as a "user" bring up totally new aspects, that we - as coders - don´t take into account,. And thats totally okay ;)

**Comment by holger1411** [comment]
👍
I merge your pull request and remove "role="button" again from the hamburger icon nav
The only thing I rejected it the addition of gulpfile.js to the .gitignore file.

If you install UnderStrap via `npm install understrap` it will not ship the gulp file if it is on the ignore list...as far as I know.... :question:
See. https://github.com/holger1411/understrap/commit/85a6d42c00e866c082a20b0d68aa31088bfbc711

**Comment by holger1411** [comment]
I close this now.
@Thomas-A-Reinert: Feel free to reopen this or create a new issue as soon as you get an answere from the BS guy. Maybe it is a feature, maybe it is a bug... :santa:

**Comment by Thomas-A-Reinert** [comment]
Sorry for the .gitignore. I´m just working on it and it´s still not perfect, so I added it to .gitignore to avoid any problems for any other user.

**Comment by holger1411** [comment]
No problem!

**Comment by holger1411** [comment]
Committed 4:40 ... seems you have a short night;-)
