### ISSUE TITLE
Author archive missing a translation

### ISSUE THREAD

**Issue by VesterDe** [holger1411/understrap#107]
author.php line 58 is this line:

`<?php the_time('d M Y'); ?> in <?php the_category('&');?>`

That "in" would need to be translated. Or rather, the entire line needs some way to get translated.

I don't know what the best approach is here. I can write it up, but I'd appreciate some comments on the options. I can think of these, quickly:

`<?php printf('%s %s', the_time('d M Y'), __('in', 'understrap')); ?>`
`<?php the_time('d M Y'); _e('in', 'understrap'); the_category('&');?>`

**Comment by Thomas-A-Reinert** [comment]
I´d rather stick to the time format that can be set up via the admin-interface.
My suggestion would be
`<?php understrap_posted_on(); ?> <?php esc_html_e( 'in', 'understrap' ); ?> <?php the_category('&');?>`

Writing that I also see that understrap_posted_on() needs improvement, because there is no separator between posted on and updated. Will contribute both in a later pull request.

**Comment by Thomas-A-Reinert** [comment]
NP
