### ISSUE TITLE
Im having this issues while im executing npm install 

### ISSUE THREAD

**Issue by asiz15** [holger1411/understrap#121]
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/underscores-for-npm
npm ERR! 404 
npm ERR! 404  'underscores-for-npm' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'understrap'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:

**Comment by holger1411** [comment]
Hi!
The problem is that the npm pack has an spelling eroor.
It is called "undescores-for-npm" instead of "underscores-for-npm"
We fixed that in the UnderStrap package.json file...but of course the package itself keeps its wrong name.

I revert the fix so that UnderStrap loads the right package (...with the wrong name) again, till I correct tha package name.

If you want to fix it by your own open your package.json file and search for:
`"underscores-for-npm": "^1.0.0"`
change it back to:
"undescores-for-npm": "^1.0.0"

Or download the latest the latest version here from GitHub
