### ISSUE TITLE
Getting started with child theme

### ISSUE THREAD

**Issue by bdube30** [holger1411/understrap#15]
Hi,

I want to use Understrap for a project, but I have an issue with using the child theme. The issue, is that the bootstrap override in  _theme_variables.scss was not taken into account. But the varaibles define inside was accessible in the child theme stylesheet.

So I want to know if I done something wrong while installing Understrap and his child theme. There the steps I've follow  : 

1- I've put the understrap folder into the Wordpress themes folder
2- I've put the understrap-child folder into the Wordpress themes folder
3- In the child theme, I've done a `npm install` follow by an bower install
4- In the child theme, I've done a` gulp copy-assets` command
5- In the child theme, I've done a` gulp watch` command
6- In the file `_theme_variables.scss` I have change the `$brand-primary` value
7- I have refresh the home page, and the color have not change.
8- I have check, the gulp watch task is executed without error.

So do I have done something badly ?

Information on my system : 
- Windows 10
- NPM version 1.4.28
- Bower version 1.7.7
- Gulp version 3.9.1

Thanks for your time,

Benjamin

**Comment by holger1411** [comment]
Hi!
Can´t reproduce the problem here.
But your process is correct.

But:
The "gulp watch" task starts the compiling task (gulp sass) and minify task. Both run simultanious. If the minify task is faster than the compile task it minifies the old css file before the new one is available.
Try the following:
- Add something new to the sass file (a line break or something like that) and save it (to start the watcher task) again.
- Refresh the page.
- Check if you see the changes now
- Let me know

If this is the case I need to rearrage the gulp tasks a bit...

Another "cowboy style" solution would be to change the css url in the child themes function.php from:
understrap-child.min.css
to
understrap-child.css
while you develope your theme on your local computer.

**Comment by Thomas-A-Reinert** [comment]
Just as a sidenote: As promised I´m currently working on an improved gulpfile.js .

It currently still has some little bugs and needs some small tweaks. But it should be able to solve above mentioned problem as the files will be queued in intended order. Hopefully I´ll commit it next week if nothing unpredictable happens.. ;)

**Comment by holger1411** [comment]
@Thomas-A-Reinert : Great! Looking forward...I´am switched from Grunt to Gulp...I´am still new to this async tasking thing,-)

**Comment by bdube30** [comment]
Thank for answer @holger1411  and @Thomas-A-Reinert .

I've try to make a little change to sass file, it still not taken in account the bootstrap variable override.

I've also try the "cowboys" solution to change css path for the un-minified one in my functions.php, this change nothing either :(

I have try on a new project, to use just a parent theme (understrap) and it work perfectly. It seem the problem is juste with the child theme.

Thanks

**Comment by holger1411** [comment]
Ah, found it.
The problem was just the wrong sequence of files in scss/understrap-child.scss.
theme/child_theme_variables must be loaded first to overwrite the BS variables properly.
See last commit here: https://github.com/holger1411/understrap-child/commits/master

**Comment by holger1411** [comment]
By the way: Thx for bughunting!

**Comment by bdube30** [comment]
Cool it's work ! Thank for fast answer ang bugfixe :)

**Comment by danilvpetrov** [comment]
Hi,
Sorry for bringing up the closed issue, but when using $brand-primary in understrap-child theme, in file /sass/theme/_child_theme_variables.scss. I cannot override understrap (parent) theme $brand-primary (#0CB4CE) in /src/sass/understrap/theme/_theme_variables.scss. Should not this variable be declared with !default so  it will not impact upstream declarations (i.e in child theme)?

**Comment by holger1411** [comment]
@danilvpetrov: Thanks for your feedback.
The problem was that the child theme uses Bootstrap as dependency AND incorporates the parent themes assets as dependencies (including Bootstrap as dependency ...)
So it loads the Bootstrap styles twice. At first before the child themes styles ... and after it. That overwrites all variables again with the Bootstrap defaults.

I changed it. Now the child will load just the understrap specific styles from the src/sass/understrap/understrap/understrap.scss but not all other assets/dependencies from the parent.

The /src/sass/understrap/theme/_theme_variables.scss. file isnt used anymore (...for the child theme...). Thats the parent theme specific design variables. The child theme use its own theme and variable scss files´s instead. Check this commit:https://github.com/holger1411/understrap-child/commit/589193103b56ca1a67e3d4490d7cf984772004a8#diff-3d6b997990ca640976e27def1f227260

**Comment by danilvpetrov** [comment]
@holger1411 Thank you very much for your response. Your solution is a good way to go, considering the fact that bootstrap sass files were loaded twice in child and parent themes. Thank you again for your work, it surely helps organizing WP themes. I also love the fact that you are using Gulp for asset management.

**Comment by EricaLynnFL** [comment]
I don't know if this was solved and bugged out again .. but my gulp is minifying my child theme before its compiling the sass .. the 'cowboy style' solution works for me .. but does anybody have any tips to slow down the minify step? 

Here's my watch output if it helps: 

[10:49:06] Starting 'sass'...
[10:49:06] Finished 'sass' after 493 ms
[10:49:06] Starting 'minify-css'...
[10:49:06] Finished 'minify-css' after 2.06 ms

**Comment by 3rdeyepro** [comment]
Having this issue too, my minify doesn't update the file or generate a new one if I delete the file.

**Comment by SeanRParker** [comment]
I hit this issue. After trying every which way to get the CSS customizations working, I finally uninstalled the two themes and reinstalled step by step. It works now!
