### ISSUE TITLE
WooCommerce sidebar problem

### ISSUE THREAD

**Issue by holger1411** [holger1411/understrap#177]
If the WooCommerce plugin is installed and activated the primary content area is set to "col-md-12" even on non WooCommerce pages.
If a (left) sidebar is active it moves down below the main content:
![screenshot at dez 08 16-12-50](https://cloud.githubusercontent.com/assets/1568158/21015178/46d36af6-bd61-11e6-8368-e8610c26690c.png)
while a right sidebar moves above the main content.

If I set 
`		$is_woocommerce = true;`
to
`		$is_woocommerce = false;`
in:
https://github.com/holger1411/understrap/blob/master/global-templates/left-sidebar-check.php#L18

Seems the check above this line did not "know" if a WooCommerce page is called...?

Maybe its better to use a woocommerce.php instead of building the logic into a default template file?

@stef-k: Don´t know whats the best practice here

**Comment by stef-k** [comment]
WooCommerce support as it is now it has its own templates and should not affect template the rest of the site uses, something else is going on here.

Check the following for example with WordPress 4.7 and latest WooCommerce. I have WooCommerce always on during development in order to check for various problems, as you can see it works as it should be.

Woo page

![selection_001](https://cloud.githubusercontent.com/assets/5731388/21019433/13afadac-bd79-11e6-8e42-19ed733ad5ac.jpg)

Main site with right sidebar

![selection_002](https://cloud.githubusercontent.com/assets/5731388/21019476/3feffca0-bd79-11e6-9589-debed4ea052c.jpg)

The same with both sidebars enabled

![selection_003](https://cloud.githubusercontent.com/assets/5731388/21019487/4d4def7e-bd79-11e6-9feb-feed4d8ec898.jpg)

Another one with left sidebar only

![selection_004](https://cloud.githubusercontent.com/assets/5731388/21019507/5cc727fe-bd79-11e6-95d0-ffce01fabf2c.jpg)

Finally check the template usage on WooCommerce

![products wordpress dev - google chrome_001](https://cloud.githubusercontent.com/assets/5731388/21019585/bc112ba6-bd79-11e6-9af5-7be9ac12aded.jpg)

**Comment by holger1411** [comment]
Strange thing, I use the latest version from this Github repo on the understrap.com demo site here:
https://understrap.com/understrap/
As soon as I activate WooCommerce the right sidebar on the frontpage moves below the main content.
If I change 
$is_woocommerce;
to:
=false
in:
https://github.com/holger1411/understrap/blob/master/global-templates/left-sidebar-check.php#L18

Everything works.
It happend on the home.php page template(the demo sites frontpage), but not on single.php or page.php ...

**Comment by stef-k** [comment]
needs further investigation, perhaps someone else could comment if has the same problem.

**Comment by 0dp** [comment]
I can confirm. Have to look at the fix when I get home

**Comment by stef-k** [comment]
Unfortunately I cannot reproduce on my local dev environment. Possibly a grid problem where columns somewhere totaling > 12?

**Comment by holger1411** [comment]
No,
just a default WP Install, default WooCommerce isntall, default UnderStrap (0.5.1) install, than I could see it on -> home.php template based pages.

**Comment by holger1411** [comment]
Close this because of the removal of home.php
