### ISSUE TITLE
woocommerce/myaccount/navigation.php

### ISSUE THREAD

**Issue by coldfusion411** [holger1411/understrap#186]
This is my first open source project I've been called to contribute too and am still a newb so please let me know if this is knit picking. 

I'm thinking it would be better to use "Base nav" instead of a "list group" for the navigation?

Like this: 

```
<nav class="woocommerce-MyAccount-navigation">
	<ul class="nav">
		<?php foreach ( wc_get_account_menu_items() as $endpoint => $label ) : ?>
			<li class="<?php echo wc_get_account_menu_item_classes( $endpoint ); ?> nav-item">
				<a class="nav-link" href="<?php echo esc_url( wc_get_account_endpoint_url( $endpoint ) ); ?>"><?php echo esc_html( $label ); ?></a>
			</li>
		<?php endforeach; ?>
	</ul>
</nav>
```

**Comment by stef-k** [comment]
Hi and welcome, here is the snippet you've posted in proper highlighting, just an hour ago I found myself looking why HTML syntax highlitghing wasn't working. I've found that Github expects backticks to be on their one lines...

```html
<nav class="woocommerce-MyAccount-navigation">
	<ul class="nav">
		<?php foreach ( wc_get_account_menu_items() as $endpoint => $label ) : ?>
			<li class="<?php echo wc_get_account_menu_item_classes( $endpoint ); ?> nav-item">
				<a class="nav-link" href="<?php echo esc_url( wc_get_account_endpoint_url( $endpoint ) ); ?>"><?php echo esc_html( $label ); ?></a>
			</li>
		<?php endforeach; ?>
	</ul>
</nav>
```

**Comment by stef-k** [comment]
As for your proposal, i've implemented it that way in order to provide an appealing menu from the start and a quick and easy way was to exploit the group item classes from the list group element. All this resulted to this:

![selection_001](https://cloud.githubusercontent.com/assets/5731388/21154810/6e3958f6-c178-11e6-8896-54533e047955.jpg)

your proposal results to this

![selection_002](https://cloud.githubusercontent.com/assets/5731388/21154868/a42f0226-c178-11e6-84a6-804d9ffc8924.jpg)

both are correct approaches and I think it is a matter of taste.

Please submit a pull request so @holger1411 can review/merge it.
