### ISSUE TITLE
gulp watch, very slow. How to speed it up? especially in the cssnano.

### ISSUE THREAD

**Issue by ryanrahman26** [holger1411/understrap#197]
My RAM: 2GB
Intel Celereon Processor

gulp watch, very slow on my laptop, especially in the css nano. How to speed it up, please help ?
![1](https://cloud.githubusercontent.com/assets/20228877/21414104/29fe3266-c82f-11e6-84c8-604dbdfb625c.png)

**Comment by ryanrahman26** [comment]
tThe cssnano take 5 seconds up to 6 seconds and sometimes 9 seconds, I would be grateful if someone helps ;(

**Comment by ryanrahman26** [comment]
And this is 18 SECONDS :(, should i buy new high laptop ?

![2](https://cloud.githubusercontent.com/assets/20228877/21415387/d3dd6dc2-c83b-11e6-9131-c994a5614d2b.png)

**Comment by holger1411** [comment]
Hi!
I test it on different computers and it needs just 200 - 500 ms. 
But all of them have 8 - 16GB.
So maybe yes, it may be a good reason to buy a new computer;-)

A cheaper methode:
Instead of "gulp watch" run "gulp watch-scss" and change the css file name in your enqueue.php to "theme.css" instead of "theme.min.css" while you develope.

The "gulp watch-scss" task just watches for changes and creates the theme.css file, but not run the cssnano task.

If you are done run "gulp cssnano" once and change the css url on your live system back to theme.min.css

**Comment by ryanrahman26** [comment]
I will try the cheaper method later 😀, and report here later

Pada tanggal 22 Des 2016 14:48, "Holger" <notifications@github.com> menulis:

**Comment by VesterDe** [comment]
Also, cssnano is something you really only need for production, so you can afford to skip it for development.

Just comment out line 114 in the gulpfile, then uncomment it when you're building for production.

https://github.com/holger1411/understrap/blob/master/gulpfile.js#L114

**Comment by Frieshansen** [comment]
I had the same speed issues. By switching from cssnano to cleancss ([https://github.com/scniro/gulp-clean-css](url)) the running time (just for the minifying task) changed from ~5 sec. to ~300 ms. Without any options the size of the min.css increased from 183.173 Bytes to 185.885 Bytes (unmodified theme.css from 0.5.7, specialComments left in).

**Comment by holger1411** [comment]
Thx for that hint.
Will try it, too. If everything works fine I will replace it

**Comment by up637415** [comment]
That link (https://github.com/scniro/gulp-clean-css) is broken. What I ended up doing is commenting out line 105 in the understrap/gulpfile.js and turning off cssnano:

`// Run:
// gulp watch
// Starts watcher. Watcher runs gulp sass task on changes
gulp.task('watch', function () {
    gulp.watch('./sass/**/*.scss', ['sass']);
    //gulp.watch('./css/theme.css', ['cssnano']);
    gulp.watch([basePaths.dev + 'js/**/*.js','js/**/*.js','!js/theme.js','!js/theme.min.js'], ['scripts']);
});`

And then changing understrap/inc/enqueue.php to include the unminified version of the CSS:

`	function understrap_scripts() {
		// Get the theme data.
		$the_theme = wp_get_theme();
		//wp_enqueue_style( 'understrap-styles', get_stylesheet_directory_uri() . '/css/theme.min.css', array(), $the_theme->get( 'Version' ) );
		wp_enqueue_style( 'understrap-custom', get_stylesheet_directory_uri() . '/css/custom-editor-style.css', array(), $the_theme->get( 'Version' ) );`

**Comment by kpschaper** [comment]
The link is not broken for me?
This css-minifiy specifies that clean-css should be one of the fastests:
https://github.com/GoalSmashers/css-minification-benchmark
gulp-clean-css is just a gulp wrapper for clean-css

**Comment by GuerrillaCoder** [comment]
i5 + 16gb ram `gulp watch-bs` takes about 4s to compile.  `gulp watch-scss` compiles in 15ms.

**Comment by holger1411** [comment]
Ive already replace cssnano with minify-css. Will be shipped with the next release.
Thx for helping me out to find and debug this problem!

**Comment by christian70** [comment]
Excuse me, gulp watch-bs run very fast (few ms) in my Understrap theme copy, but if I use Understrap child theme the cssnano slows it down and down (up to 6/7s). Is there any way to run it as fast as in parent theme?

**Comment by holger1411** [comment]
I replaced the cssnano task with minify-css in the latest child theme version 0.3.0 too. So it should be as fast as the parent theme now

**Comment by smartbrat** [comment]
My Gulp watch Task runs extremely slow I don't know if the problem is with my system hardware or with the setup of gulp environment.

`var settings = {
	clean: true,
	scripts: true,
	polyfills: true,
	styles: true,
	critical: false, // check
	purge: false, // check
	images: true,
    fonts: true,
    copy: true,
	reload: true
};


/**
 * Paths to project folders
 */

var paths = {
	input: 'src/',
	output: 'dist/',
	scripts: {
		input: 'src/js/*',
		polyfills: '.polyfill.js',
		output: 'dist/js/'
	},
	styles: {
		input: 'src/sass/**/*.{scss,sass}',
		output: 'dist/css/'
	},
	images: {
		input: 'src/img/**/*',
		output: 'dist/img/'
	},
	copy: {
		input: 'src/copy/**/*',
		output: 'dist/'
	},
    fonts: {
        input: 'src/font/*',
        output: 'dist/font/'
    },
	reload: './dist/'
};


/**
 * Gulp Packages
 */

// General
var {gulp, src, dest, watch, series, parallel}        = require('gulp'),
    del = require('del'),
    flatmap = require('gulp-flatmap'),
    lazypipe = require('lazypipe'),
    rename = require('gulp-rename'),

    // Scripts
    jshint = require('gulp-jshint');
    stylish = require('jshint-stylish');
    concat = require('gulp-concat');
    uglify = require('gulp-terser');
    optimizejs = require('gulp-optimize-js');
    
    // Styles
    sass        = require('gulp-sass')(require("node-sass")),
    postcss = require('gulp-postcss'),
	sourcemaps = require('gulp-sourcemaps'),
    precss = require('precss'),
    prefix = require('autoprefixer'),
	minify = require('cssnano'),

    // Remove unused, generate critical css and inject into html
	rename = require('gulp-rename'),
    purgecss = require('gulp-purgecss'),
	critical = require('critical').stream,

    // Images Minification
    imagemin = require('gulp-imagemin'),
    
    // Log Generation
    log = require('fancy-log'),

    browserSync = require('browser-sync').create();


/**
 * Gulp Tasks
*/

// Remove pre-existing content from output folders
var cleanDist = function (done) {

	// Make sure this feature is activated before running
	if (!settings.clean) return done();

	// Clean the dist folder
	del.sync([
		paths.output
	]);

	// Signal completion
	return done();

};


// Repeated JavaScript tasks
var jsTasks = lazypipe()
	//.pipe(header, banner.main, {package: package})
	.pipe(optimizejs)
	.pipe(dest, paths.scripts.output)
	.pipe(rename, {suffix: '.min'})
	.pipe(uglify)
	.pipe(optimizejs)
	// .pipe(header, banner.main, {package: package})
    .pipe(dest, paths.scripts.output);
    
// Lint, minify, and concatenate scripts
var buildScripts = function (done) {

	// Make sure this feature is activated before running
	if (!settings.scripts) return done();

	// Run tasks on script files
	return src(paths.scripts.input)
		.pipe(flatmap(function(stream, file) {

			// If the file is a directory
			if (file.isDirectory()) {

				// Setup a suffix variable
				var suffix = '';

				// If separate polyfill files enabled
				if (settings.polyfills) {

					// Update the suffix
					suffix = '.polyfills';

					// Grab files that aren't polyfills, concatenate them, and process them
					src([file.path + '/*.js', '!' + file.path + '/*' + paths.scripts.polyfills])
						.pipe(concat(file.relative + '.js'))
						.pipe(jsTasks());

				}

				// Grab all files and concatenate them
				// If separate polyfills enabled, this will have .polyfills in the filename
				src(file.path + '/*.js')
					.pipe(concat(file.relative + suffix + '.js'))
					.pipe(jsTasks());

				return stream;

			}

			// Otherwise, process the file
			return stream.pipe(jsTasks());

		}));

};

// Lint scripts
var lintScripts = function (done) {

	// Make sure this feature is activated before running
	if (!settings.scripts) return done();

	// Lint scripts
	return src(paths.scripts.input)
		.pipe(jshint())
		.pipe(jshint.reporter('jshint-stylish'));

};

// Process, lint, and minify Sass files
var buildStyles = function (done) {

	// Make sure this feature is activated before running
	if (!settings.styles) return done();

	// Run tasks on all Sass files
	return src(paths.styles.input)
		.pipe(sass({
			outputStyle: 'expanded',
			sourceComments: true
		}))
		.pipe(sourcemaps.init())
		.pipe(postcss([require('precss'), require('autoprefixer') ]))
		/* .pipe(postcss([
			prefix({
				cascade: true,
				remove: true
			})
		])) */
		.pipe(dest(paths.styles.output))
		.pipe(rename({suffix: '.min'}))
		.pipe(postcss([
			minify({
				discardComments: {
					removeAll: true
				}
			})
		]))
		.pipe(dest(paths.styles.output))
};


// Optimize Images
var buildImgs = function (done) {

	// Make sure this feature is activated before running
	if (!settings.images) return done();

	// Optimize Images files
	return src(paths.images.input)
        .pipe(imagemin([
            imagemin.gifsicle({interlaced: true}),
            imagemin.mozjpeg({progressive: true}),
            imagemin.optipng({optimizationLevel: 5}),
            imagemin.svgo({
                plugins: [
                {removeViewBox: true},
                {cleanupIDs: false}
                ]
              })
            ]))
		.pipe(dest(paths.images.output));
};

// Copy static files into output folder
var copyFiles = function (done) {

	// Make sure this feature is activated before running
	if (!settings.copy) return done();

	// Copy static files
	return src(paths.copy.input)
		.pipe(dest(paths.copy.output));

};

var purgestyles = function (done) {

	// Make sure this feature is activated before running
	if (!settings.purge) return done();

    return src('./dist/css/*.css')
		.pipe(rename({
			suffix: '.rejected'
		}))
        .pipe(purgecss({
			content: ['./dist/*.html', './dist/js/*.js'],
			rejected: true
        }))
        .pipe(dest('./dist/css'))
};


// Critical Path CSS - Generate Above the fold css and inject into html head after generating final html files in dist folder
var criticalHome = function (done) {
	
	// Make sure this feature is activated before running
	if (!settings.critical) return done();

	// Critical CSS
	return src('dist/index.html')
		.pipe(critical({
		base: paths.reload,
		inline: true,
		css: [
			'dist/css/core.min.css',
			'dist/css/home.min.css',
		]
		}))
		.on('error', err => {
		log.error(err.message);
		})
		.pipe(dest(paths.reload));

};


var criticalBlog = function (done) {
	
	
	// Make sure this feature is activated before running
	if (!settings.critical) return done();

	// Critical CSS
	return src('dist/blog-details.html')
		.pipe(critical({
		base: paths.reload,
		inline: true,
		css: [
			'dist/css/blog-details.min.css'
		]
		}))
		.on('error', err => {
		log.error(err.message);
		})
		.pipe(dest(paths.reload));

};


// Watch for changes to the src directory

var startServer = function (done) {

	// Make sure this feature is activated before running
	if (!settings.reload) return done();

	// Initialize BrowserSync
	browserSync.init({
		server: {
			baseDir: paths.reload
		}
	});

	// Signal completion
	done();

};

// Reload the browser when files change
var reloadBrowser = function (done) {
	if (!settings.reload) return done();
	browserSync.reload();
	done();
};

// Watch for changes
var watchSource = function (done) {
	watch(paths.input, series(exports.default, reloadBrowser));
	done();
};


/**
 * Export Tasks
 */

// Default task
// gulp
exports.default = series(
	cleanDist,
	parallel(
		buildScripts,
		lintScripts,
		buildStyles,
		buildImgs,
		copyFiles,
	),
	purgestyles,
	criticalHome,
	criticalBlog,
);

// Watch and reload
// gulp watch
exports.watch = series(
	exports.default,
	startServer,
	watchSource
);`

Kindly help. Everytime I save the file after edits the task completion takes way too long and I lose a lot of time in delivering the work. I am not from a programming background so please be kind.
