### ISSUE TITLE
Ubnderstrap-bs3 or 4?

### ISSUE THREAD

**Issue by TRE8** [holger1411/understrap#206]
Just wanted to ask if it will be easy to switch from UnderStrap-bs3 to -bs4 theme?

**Comment by holger1411** [comment]
Normally yes, but it depends if you already use a child theme with a lot of changes and/or if you have a lot of content/components based on Bootstrap3

**Comment by ChrisChiera** [comment]
Going to experiment with understrap bs4 for internal testing, but for a live production project would need to use the stable BS3, since BS4 is still in Alpha and also no IE9 support.

I see most all the files haven't been updated in over 7 months. In regards to WooCommerce I see in the BS3 version its simply one file that adds support, where is BS4 has more in that file an a whole woocommerce folder. Would replacing adding that bs4 woocommerce folder to bs3 and updating the bs3 woocommerce.php file with the bs4 one work? Other than possibly updating a few class names? Or are there a lot of other changes that would be necessary? Thanks for any guidance you maybe able to provide.

**Comment by typeplus** [comment]
@ChrisChiera I basically decided to forge ahead with 0.5.1 over the latest release which switches over to flexbox only. From analytics I know there is a huge chunk of users of the site I am redeveloping which use IE so I cant switch.

**Comment by holger1411** [comment]
It depends on your project. BS4 will not support IE9 or lower, definitely. So if you have a project with alot of IE9 users you should stick with BS3
