### ISSUE TITLE
Header broken with container-fluid

### ISSUE THREAD

**Issue by bolgerandbattle** [holger1411/understrap#219]
When setting the theme to full-width layout (container-fluid), the header breaks. Container-fluid is missing the following elements from `.navbar-toggleable-md>.container`: 
`display: flex;
flex-wrap: nowrap;
align-items: center;`

It also requires setting `width:100%`, otherwise it's squished in the middle of the viewport.

Screenshot [https://goo.gl/photos/WXCYjWBB5Zd6RWvu7](https://goo.gl/photos/WXCYjWBB5Zd6RWvu7)

**Comment by jznadams** [comment]
FYI, there are a [number of open issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20nav%20container) with containers and navbars in the main bootstrap repo for beta v6

**Comment by holger1411** [comment]
Yeah, the problem is that .containers inside the navbar break the navigations functions for some reasons since Alpha 6. So I removed´em.
I will check if it is a BS bug or if there is already a solution for it which I can implement.

**Comment by holger1411** [comment]
Okay, the BS guys just use no .container <div> on a fluid layout and just the default .container on a boxed layout on there demo sites.
Don´t know if it is a workaround or just the way you should use it.
Will try to implement it.

**Comment by holger1411** [comment]
Okay here is the fix:
https://github.com/holger1411/understrap/commit/fda8575b1aab26e2fbfc6ce03257d37cbc355fc7
I just check if the variable is set to "container". The it adds a `<div class="container">` and a ending `</div>`.
If the variable is set to something else nothing happends and no extra container markup will be added.
Don´t know if it is just a workaround/dirty-fix.
But the fulid BS navbar never required a container-fluid div since now, so it seems to be a clean solution.
