### ISSUE TITLE
Don't deploy dev files to dist/

### ISSUE THREAD

**Issue by Routhinator** [holger1411/understrap#237]
Currently this package deploys a lot of unwanted files in it's 'distribution'.

- gulpfile.js
- package.json
- README.md
- bower.json
- CHANGELOG.md
- sass/

They should be omitted when generating the dist/ folder.

**Comment by holger1411** [comment]
Hi!
The dist task is used to pack up UnderStrap for the wordpress.org theme repo.
It just removes the /node_modules and /src folder and some minor stuff.

Especially because UnderStrap is more a dev framework or a starter theme for theme dev´s it should include anything to setup a dev enviroment. There are just a few ppl who use it "as-it-is".

I tried it without all this stuff some time ago. But received too much "where are the sass source files?" support requests.

And there are users who develop free or commercial themes out of UnderStrap. They also need a task which adds any resources needed to work with into there distribution to release it as product.
...
Hm, but it might be a good idea to have two differnt "dist" tasks. 
One to create a shipable product (with dev resources), and one to deploy it to your server (without the resources)...

**Comment by holger1411** [comment]
Okay, now there are two tasks:
https://github.com/holger1411/understrap/commit/a3b02f6743618dd62dadd58406ccf788e762ea39

`gulp dist`
creates a clean distribution without any dev stuff

`gulp dist-product`
creates a /dist-product folder with anything inside you need it to release it as "product".
For example if you wanna offer it as theme download, publishing it on wordpress.org etc.

**Comment by holger1411** [comment]
@Routhinator Close this, but feel free to comment/reopen if you have more ideas/questions/feedback on this is issue

**Comment by Jaafarw** [comment]
I am confused, here is what my dist folder is showing:

![image](https://user-images.githubusercontent.com/41353910/49451718-190fc900-f7e0-11e8-8176-d42bb005e22e.png)

And the dist-product folder:

![image](https://user-images.githubusercontent.com/41353910/49451853-596f4700-f7e0-11e8-8aa0-51008f6874b2.png)

Isn't it supposed to be the other way around?
