### ISSUE TITLE
Bootstrap CSS missing col-xs

### ISSUE THREAD

**Issue by mkavanti** [holger1411/understrap#262]
In the last couple of versions of the theme and child theme it looks like the CSS for col-xs-1 etc is no longer present in the stylesheets. It looks like it has been replaced with just col-1 etc meaning the '-xs' is no longer there. Thanks for the amazing work on this theme.

**Comment by holger1411** [comment]
Yes, the theme integrates the latest Bootstrap 4 version. See: https://v4-alpha.getbootstrap.com/layout/grid/#grid-options

The `col-xs-1` class is no longer needed and replaced by `col-1`. Add a size just if you need a breakpoint bigger than xs. For example `col-md-1` or `col-lg-1`

Even just `col` works as class. Than all columns in one row will adjust its size automatically so that all fit in on all screen sizes having the same horizontal width.

**Comment by mkavanti** [comment]
Understood. Thanks for clarifying that. Woocommerce uses the same class (col-1 etc) in its default layout - not sure if this creates any issues.

**Comment by holger1411** [comment]
Hm, good question. UnderStrap comes with its own templates for WooCommerce. So if we did not miss anything there should be no problem.
The UnderStrap CSS is loaded after the WooCommerce css files so the BS4 styles *should* apply.
Will keep an eye on this.
