### ISSUE TITLE
Bootstrap tooltips require Tether

### ISSUE THREAD

**Issue by dvlopes** [holger1411/understrap#27]
I'm trying to include my own scripts for a child theme and am getting this javascript error:

`Uncaught Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)`

As in the Bootstrap 4 documentation, tether should be included in the project:
[http://v4-alpha.getbootstrap.com/components/tooltips/#overview](http://v4-alpha.getbootstrap.com/components/tooltips/#overview)

Even tough I'm developing a child theme, in my opinion it should be included as a dependence in the Understrap Framework.

I will try to include it in the project and submit a pull request, but as I am new to bower and project dependencies it might take a while (anyone to help me along?).

Anyways, if anyone starts working on this issue please let everybody know :grin:

**Comment by holger1411** [comment]
Yeah I know, problem is that I don´t wan´t to include another 3rd party script just in case someone want to use the (optional) tooltip component in BS4 (the theme itself don´t us it). Even the BS4 sample demos don´t use it (and you will see the JS message...). And it seems the tether script must be loaded as extra script...it did not work if I compile it into the theme.min.js file along with BS4.

My problem is that the theme has to do another extra request and load another 23kb script...without any usage for 99.99% of all visitors.

But if I remove the tooltip component from BS4 the dropdown function did not work anymore...seems it use some snippets from this component.

Because BS4 is still in Alpha stadium I could live with it, hoping they found another solution/way for it.
If you found it let me know!

**Child as dependency?**
The child theme ist not a dependency from the parent theme, but the parent theme is already a dependency from the child theme;-)

The child uses a lot of stuff from the parent, but the parent don´t use anything from the child.
Or with other words: The child theme "depends" on the parent, but the parent did not "depend" on the child.

**Comment by dvlopes** [comment]
Ok. I'm not gonna use tooltips for this project either but my scripts don't work because of that. It works if I use bootstrap sprockets and do not load tooltips component.

I think it would be good to remove tooltips by default from the parent project and put info in the readme file on both projects.
It will prevent problems like mine. What you think?

> Child as dependency?

No. Sorry for the confusion, I was really tired when I wrote that haha.
I meant to put Tether as a dependency in the parent project, but forget that, you already gave reasons not to =D

**Comment by dvlopes** [comment]
Here is what I changed in gulpfile.js to compile my scripts:
[https://github.com/dvlopes/understrap-child/blob/jveventos/gulpfile.js#L91](https://github.com/dvlopes/understrap-child/blob/jveventos/gulpfile.js#L91)

**Comment by holger1411** [comment]
Problem is if I don´t compile the BS tooltip.js file into it, the dropdown menu stops working and I receive this error:
TypeError: r.default is undefined

As far as I could see it you override (or simulate) the BS dropdown function by your own js, right?
Might be an option, but isnt the cleanest one, too for a theme framework.

There are ongoing discussions in the BS4 forums/git repo about managing theter as dependency. Will wait a bit till they found there direction...

**Comment by holger1411** [comment]
Found a solution. Seems the problem was that I try to compile the tether.min.js into the theme.min.js file. If I add the Tether script as dependency and compile the non-minified tether.js before Bootstrap.js it seems to work. See changes here:
https://github.com/holger1411/understrap/commit/862fd60b641c664070bb74e4ec31a9985dd2870a

Means I don´t need another request for theter and the error message is gone, but the theme.min.js file will be about 20kb bigger. Its not a perfect tradeoff but better than nothing...

**Comment by dvlopes** [comment]
> As far as I could see it you override (or simulate) the BS dropdown function by your own js, right?
> Might be an option, but isnt the cleanest one, too for a theme framework.

Yeah, I didn't consider using BS dropdown because it is for a sidebar menu, but I'll try it later on this project.

With the new release v0.4.3 the script is compiling and working well. Thx
