### ISSUE TITLE
Gulp corrupting png images?

### ISSUE THREAD

**Issue by matriplett** [holger1411/understrap#307]
Has any else experienced images being corrupted in the img folder. I'm guessing it's a gulp issue?

**Comment by washaweb** [comment]
Yes, I've encountered this problem too. I noticed that imagemin task was like in an infinity loop just before my images went corrupted.

**Comment by washaweb** [comment]
I temporarily solved the problem by adding a folder images as source and changed the gulpfile script:

```
gulp.task('imagemin', function(){
    gulp.src('images/**')
    .pipe(imagemin())
    .pipe(gulp.dest('img'))
});
```

**Comment by matriplett** [comment]
Thanks so are you adding an additional folder called images or renaming?
Then in addition to the gulp change above, also change:
```    //Inside the watch task.
    gulp.watch('./images/**', ['imagemin'])
});```

**Comment by matriplett** [comment]
I also noticed I'm getting 
```Task 'default' is not in your gulpfile

**Comment by washaweb** [comment]
indeed, you have to put your files in the `images` folder, and launch `gulp imagemin` once done. It will create the `img` folder with optimized images in it for you. 
I removed `imagemin` task from `gulp watch` and gulp watch-bs` because if not, it will continue to corrupt the files. 
It may not be the best way to do it, but most of the time, I add images at the beginning and then start to build the css. So if you later add some images, don't forget to run the 'imagemin' task again.

**Comment by matriplett** [comment]
thank you!

**Comment by holger1411** [comment]
Thx to both of you!
Seems the input and output folder could not be the same...
I created a new folder called /img/src
Images from there will be minified and than be stored one folder up in /img

**Comment by washaweb** [comment]
Sorry but I still have the problem, even with the /img/src folder.
