### ISSUE TITLE
Some problem with compiling from scss

### ISSUE THREAD

**Issue by birdm99** [holger1411/understrap#43]
Hello:)
I have some problems with compiling from scss. Each time I try to compile Koala says /Users/myuser/Documents/Projekty/przedszkole/sass/child-theme.scss
Error: Invalid US-ASCII character "\xC2"
        on line 6 of /Users/myuser/Documents/Projekty/przedszkole/sass/child-theme.scss
  Use --trace for backtrace.

Can you help??

**Comment by holger1411** [comment]
In line 6 of the child-theme.scss file is just a comment:
> //Optional files - If you don´t use the corresponding scripts/fonts comment em out
seems the "´" is the problem. Because your Koala did not use UTF8 encoding but US-ASCII.

I don´t know the tool itself but you should be able to change the encoding somewhere. UTF8 is the way to go. With another encoding you might have problems in various ways
An easy solution would be to just delete the comment.
