### ISSUE TITLE
Hero not working on home page

### ISSUE THREAD

**Issue by codeThaGlobe** [holger1411/understrap#432]
I am on the home page, but no hero is being created.
I created image widgets in the static hero widget area, but no hero.

I have looked through the files and templates, but this should be automatic.

**Comment by codeThaGlobe** [comment]
In index.php is the following:

<?php if ( is_front_page() && is_home() ) : ?>
	<?php get_template_part( 'global-templates/hero', 'none' ); ?>
<?php endif; ?>

I am on the static home page and the class "home" is on the body tag.

**Comment by axlright** [comment]
Works fine for me. Here's an in-production site I'm working on using the hero static widget area: https://vacayvans.wpengine.com/

I renamed index.php into home.php but I assume it should work either way.

Can you send more details?

**Comment by codeThaGlobe** [comment]
For all software / framework / theme developers. When you build a product and advertise or put out a demo, it should not take hours of poking around for someone to get the same result as what you sold them on. It should "work as advertised", period.

Be creative, include a mysql dump of demo data if needed, but don't show something that you - the developer, see as obvious (since you built it) but the novice user will have to struggle to get to. This is what UX is all about. Considering and being empathetic to the user of your product, guiding them with onboarding and showing you understand their needs. That is where great companies differ from the others.

**Comment by axlright** [comment]
I was able to get going pretty quick on about 10 client projects. I think this is where open source free software can benefit from community involvement. No one's making money off this. GitHub is a great platform for contributing where you see fit. @holger1411 has been pretty amazing with developing this framework, and the community is supporting others. That's a great way to start.

**Comment by shansmith01** [comment]
@codeThaGlobe considering this is open source and community based I think you should be pretty stoked about what you are getting here. I have zero experience with NPM, GULP and the more tech aspects of theme dev and I was able to get a basic site up and running in 15 min and a fully functioning dev enviro running with wpengine in about 2 hours. I agree docs would be useful and that's why I plan on contributing some docs in time. Perhaps you could help too?

**Comment by codeThaGlobe** [comment]
The reality is, if you get a product and it doesn’t work “as advertised” there is a negative user experience. That happens wether it was built by a major corporation or a community of passionate, well-intentioned and altruistic developers.

**Comment by axlright** [comment]
Maybe it's your bad attitude that's getting in the way? You're not going to win any friends or get any help with this kind of approach.

**Comment by typeplus** [comment]
`page.php` is the one you need to target if you are not working on the page which shows your latest posts. Something like this;
```
<?php if ( is_front_page() ) : ?>
	<?php get_template_part( 'global-templates/hero', 'none' ); ?>
<?php endif; ?>
```

Inserted at line 19 on the `page.php` will make sure the hero shows on the front page.

@holger1411 (especially) and all contributors do an amazing job with this theme and support provided.

**Comment by holger1411** [comment]
@codeThaGlobe: You are welcome to contribute to the docs repo for understrap: https://github.com/understrap/understrap.github.io

> This is what UX is all about. Considering and being empathetic...

Try to be empathic and imagine the following:
1. You are a contributer to an open source project
2. You dont get payed for your work and time you spend in your rare spare time
3. You have to work 8hrs+ (per day) elsewhere to pay your bills
4. You have kids, hobbies, a familiy. Maybe you have to take care of your parents etc.
5. You have 1 or 2 hrs per week left for the open source project
6. Than someone comes around and says: "Spend more of your free time because I don´t want to spend my spare time to digg deeper in your free and open source project which I can use freely to earn money with it. I expect a perfect product like from Apple, Google or another major corporation!"
7. What would you think about such a person?  

I´am sure that you, as a good UX designer, are able to shift your POV and will find some good answeres to 7.

**Comment by kjostling** [comment]
@holger1411 don't spend time and energy to answer morons. Your doin great, thanks!

**Comment by sbdm05** [comment]
Thanks to all the contributors of this great theme ! I just have to say I am running into the exact same "issue". HomePage is set up as homepage. I clearly see the get_template_part ('global-templates/hero') in index.php. I added an image in the dashboard>widget hero static. Any idea ? thank you!

**Comment by Thomas-A-Reinert** [comment]
Please see: https://github.com/holger1411/understrap/issues/557
