### ISSUE TITLE
custom-comments.php

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [holger1411/understrap#451]
Line 24, missing closing div-bracket:
`'author' => '<div class="form-group comment-form-author"> <label for="author">' . __( 'Name',`

Validating it also shows two more errors but I can´t resolve where those come from. They´re inserted in the textarea field/s (what is the first one anyway?): 
> line 246: Bad value “nope” for attribute “autocomplete” on element “textarea”: The string “nope” is not a valid autofill field name.

Correct value would be "off".

**Comment by holger1411** [comment]
Hi!
The closing tag is on line 26:172
To the second issue:
Hm, can´t find any sutocomplete="nope" markup within the UnderStrap code. Maybe its a plugin or something?
Where do you get the validation error (which page)?

Thx in advanced!

**Comment by holger1411** [comment]
Arh, sorry.
Your first reported bug was fixed here:
https://github.com/holger1411/understrap/pull/427/commits/7dec63645496c2f841e9b8a1a3ae12807f596ecb
in version 0.6.6

But because it is available here on Github only, all users who installed it from there WordPress backend will get still 0.6.5 which included the bug.

So download the file here from github and replace the non-fixed version with it till the new 0.6.7 version is available.

**Comment by Thomas-A-Reinert** [comment]
Thanks for the info @holger1411 and sorry for the late response!

For the second problem with autocomplete="nope" - cannot reproduce it anymore since the site has gone live?! Will observe it though with any other site I´m building and keep this specific site under surveillance too.
