### ISSUE TITLE
Hero Slider not working

### ISSUE THREAD

**Issue by revamperdiaries** [holger1411/understrap#457]
I am working on Hero Slider. Unfortunately, it won't work properly and services displays this error. 

"JQuery not defined"

![untitled](https://user-images.githubusercontent.com/21028729/32696303-bdca053a-c7af-11e7-95c2-4aa209621330.png)

**Comment by holger1411** [comment]
Hi!
There is currently a problem with the jQuery version used by WordPress and which is required by Bootstrap 4 Beta 2.
The Bootstrap guys working on a fix, which will be released with Bootstrap 4 Beta 3.
For the moment I would suggest to use the latest UnderStrap version 0.6.5 which is available on WordPress.org (0.6.6 was not released there because of the bug):
https://wordpress.org/themes/understrap/

**Comment by revamperdiaries** [comment]
Got that! Thanks!
