### ISSUE TITLE
where do I add custom JS ?

### ISSUE THREAD

**Issue by Ionut-Milas** [holger1411/understrap#47]
What's the procedure for adding custom Javascript/jquery code ?

**Comment by holger1411** [comment]
Hi!
Just add your js file wherever you want (...but inside the understrap folder) and add the path to the gulp task "gulp script"  in gulpfile.js starting here:
https://github.com/holger1411/understrap/blob/master/gulpfile.js#L90

Than run "gulp scripts" to compile your JS (along with the other scripts) into one minified and uglified JS file called theme.min.js (which is used by the theme).

**Comment by Ionut-Milas** [comment]
Great. Thank you.
another thing that I noticed....
I'm use @import in _theme.scss.
the scss partials are structured in folders, 
I make changes in a partial but those changes are not compiled until I save _theme.scss again ...

It's annoying to do so..

Any Ideas ?

**Comment by holger1411** [comment]
Hi!
Seems somethimes the cssnano task is faster done than the watcher task.
Means everything is fine with your @import but it minifies the old css file some ms before the new css file was generated.
Means you have the right compiled theme.css with your new changes, but an "old" theme.min.css without your latest changes. If you change anything else the task runs again and the changes will be applied to your min.css too. It just happens if your cssnano task is faster, which depends on your settings, machine etc.
Its one of this Gulp timing problems.
I´am not a real Gulp pro, so if anyone has a fix for it let me know! Otherwise I will try to find a workaround.

**Comment by Ionut-Milas** [comment]
hello, any update on this ?

**Comment by julienhoste** [comment]
Hello, 
Does this mean I could add a custom.js file in /js/ folder from the child theme and it would be minified and uglified within theme.min.js file ? So, no more wp_enqueue_script?

Could you please, be more precise about the gulp tasks. Your comment points to https://github.com/holger1411/understrap/blob/master/gulpfile.js#L90 but this seems to concern the scss files?
Where and what should I add to take a custom js file in account?
Thanks by advance.

**Comment by typeplus** [comment]
@julienhoste  I can get this to work :(

I dont get any errors and the gulp scripts seems to process OK. Strangely checking the minified js there isnt any mention of the new code (which I have tested in the chrome console and it works).

I basically;

Created the js/child-theme-custom.js file
Added the code (which is just for input spinners to use js to update the field ;
```
jQuery(document).ready(function($){
        $('.quantity').on('click', '.plus', function(e) {
            $input = $(this).prev('input.qty');
            var val = parseInt($input.val());
            $input.val( val+1 ).change();
        });
 
        $('.quantity').on('click', '.minus', 
            function(e) {
            $input = $(this).next('input.qty');
            var val = parseInt($input.val());
            if (val > 0) {
                $input.val( val-1 ).change();
            } 
        });
    });
```
 
Then updated the gulpfile.js with these lines;
```
basePaths.dev + 'js/skip-link-focus-fix.js',
basePaths.dev + 'js/child-theme-custom.js'
])
```

Ran $gulp scripts with no errors.

At a loss here? Is that the right procedure? 

Thanks for any help guys this one got me stumped 👍

**Comment by typeplus** [comment]
Its appears the contents of the custom.js isnt being piped/concatenated to the child-theme.js or the child-theme.min.js !

**Comment by holger1411** [comment]
`basePaths.dev + 'js/child-theme-custom.js'` loads a file called child-theme-custom.js from the /js/ folder of the /src directory.
So make sure you place your script here:
/src/js/child-theme-custom.js

And NOT in the root /js/ directory
If you want to load it from the root directory /Js folder load it with just:
`'js/child-theme-custom.js'`
and without the `basePath.dev` before

**Comment by typeplus** [comment]
Thanks kindly Holger, really appreciate it. Sorry to waste your time again!

**Comment by holger1411** [comment]
No problem!

**Comment by sham2bam** [comment]
**(Not using Child Theme)**

Hi there - my issue so far is that my (custom) main.js file appears to be uglified along with everything else inside the src/js folder, but when I check the site, none of the JS works! 

I keep doing console tests and not seeing any response. The one error I keep seeing is "Bootstrap tooltips require Tether"… 

Please help. Thanks!

**Comment by holger1411** [comment]
By default the theme use the theter script and minifies and uglifies it before the BS4 js:
https://github.com/holger1411/understrap/blob/master/gulpfile.js#L137
Where do you add you main.js into the gulpfile.js?
And: Does the JS work if you remove your JS from gulpfile and recompile it?

**Comment by sham2bam** [comment]
Ah! 

Looks like the order in which I added the file in the gulpfile.js was the problem. I had placed my main.js file after the 'skip-link-focus-fix'. Thanks so much for helping me see that. Seems to be working like a charm!

**Comment by holger1411** [comment]
Yeah, there are strange things that might happends if the order isnt correct... :boom: :smile:
Some needs to be loaded before and some after other assets.

**Comment by samuelgates** [comment]
This is still unclear to me on how to add personal JS file.  I created a file called "personal-scripts.js" and placed it in the root js folder.

I then replaced the following code in both areas that it shows up in the gulp file: 

```
basePaths.dev + 'js/skip-link-focus-fix.js'
])

into

basePaths.dev + 'js/skip-link-focus-fix.js',
'js/personal-scripts.js'
])
```

After I ran 'gulp scripts' my sass file fails to compile until I revert the entire gulp file back to his previous state before editing. I am also unable to update my personal-scripts.js file without running gulp scripts every time I make an edit.

**Comment by holger1411** [comment]
Hi!
your code looks right. If your SASS compiling failed it sounds more like a syntax error in your gulpfile or another problemem related to your scss files.

What error message do you receive?

You are right about the watcher task. It just watches the /src/js folder for changes but should also watch the /js/ folder. The problem is that it compiles the dependency JS files from /src/js to the /js folder.
Means the watcher will start twice.
I will try to find a solution for it.

**Comment by holger1411** [comment]
Okay here is the fix for your first problem: https://github.com/holger1411/understrap/commit/6ca1abff0813a27bd0b445e12c70dd700844295e

The "gulp watch" task now watches the /js folder in the themes root folder, too. But the theme.js and theme.min.js are excluded from it.

Can´t say why your SASS task failed. Works here. 

You could remove this:
`        .pipe(plumber())`

from the SASS task in your gulpfile tempoarily. Then the task will stopp with an error message insted to skip it.
Maybe that gives us a hint where we should look at it

**Comment by samuelgates** [comment]
This worked! Thank you Holger! The SASS file is working correctly as well.

Additionally, how would you suggest properly attaching an additional library like JQuery UI to this theme?

**Comment by DEhrhardt** [comment]
Hi There... i'm having the same issue ...

I'm adding the file /src/js/mycustom.js and include it into the gulp scripts task (i tried it before and after the Line "basePaths.dev + 'js/skip-link-focus-fix.js'") like this:

    var scripts = [
        basePaths.dev + 'js/tether.js', // Must be loaded before BS4

        // Start - All BS4 stuff
        basePaths.dev + 'js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        basePaths.dev + 'js/mycustom.js',

        basePaths.dev + 'js/skip-link-focus-fix.js'
    ];

I did not even write some code in mycustom.js, but right after i execute gulp scripts i'm getting the following error: "Bootstrap tooltips require Tether"

Can anybode help?

**Comment by holger1411** [comment]
@DEhrhardt Make sure that /src/js/tether.js is present.
If not run:
`npm install`

And I would suggest not to use:
`basePaths.dev`

basePaths.dev is defined as the /src folder. So gulp checks /src/js/mycustom.js for your script.

The src folder holds all 3rd party dependencies managed via npm. If you update them the whole folder (including your code) would be deleted first and replaced with the actual versions of all dependencies.
If you don´t provide and manage your JS via npm you should place it somewhere else.
For example just use:
` 'js/mycustom.js'`
instead of
`  basePaths.dev + 'js/mycustom.js',`

**Comment by DEhrhardt** [comment]
@holger1411 

> Make sure that /src/js/tether.js is present.
the file is not present

> If not run: npm install
i ran npm install, but the file is still not present

**Comment by holger1411** [comment]
Hm, do you see this folder:
/node_modules/tether/dist/js/
in your themes root folder?

Thats what npm should create and than copy over to the /src folder.

And: Which UnderStrap version do you use?

**Comment by DEhrhardt** [comment]
@holger1411 
this folder does not exist ... 

i'm using version 0.5.7

**Comment by holger1411** [comment]
Do you receive any error messages during "npm install"?
And do you see this line in your package.json:
`    "bootstrap": "^4.0.0-alpha.6",`
?

It seems that, for some reason, your npm did not install tether along with Bootstrap 4.
another reason for this could be that you use an outdated node/npm version.
In older version npm did not installed dependencies of dependencies automatically.
Make sure your node version is at least v 6.x +
https://nodejs.org/en/

You can find out your current version by typing in `node -v` in your terminal

**Comment by DEhrhardt** [comment]
@holger1411 thanks!!! :1st_place_medal: 
there are many more files and folders now .. 

can u give me an example file-tree, how it should look like after npm install ... there are so many files now, im confused

**Comment by holger1411** [comment]
yeah, its confusing.
There are hunderts of folders and tens of thousands of files. Hard to make a screenshot from it...
But you don´t need to know whats in there.

Most files are used for Gulp, SASS or Node stuff.

The gulp task
`gulp copy-assets`
copies all files needed by the theme itself to the right folder. This task runs automatically after `npm install` , too.
So normally you don´t have to do anything if it runs without errors.

**Comment by meiskv** [comment]
Hi @holger1411 ,

I successfully added the script on to my gulpfile.js and it detects errors but the problem is on my front-end whenever I view-source my home page I don't see any custom.js on the document. May I know here should I put the script source to load it on my front-end? 

I was thinking if I added a script on my task watch it will be automatically added on the front-end or the header of the theme.

Cheers!

**Comment by meiskv** [comment]
Hi @holger1411 ,

I think I found how to add it. I saw on function.php that it was sourcing it to inc/enqueue.php. I think this is where I need to put my custom script. 👍

**Comment by televators** [comment]
So far on my current project I haven't needed to include any js but now that I'm adding something, I notice that the gulp scripts task doesn't even see the src/js folder or the dist folder. There is no dist/ directory, to start. There's src/js and js/, the latter being the dist folder, I guess. The scripts task is watching src/scripts/ and sending them to dist/scripts/, neither of which exist. So, I did this for now because I don't feel like rewriting the whole task right now:
`gulp.task('scripts', function(){
/* added 'child-theme-scripts.js', here v */
  return gulp.src(['src/scripts/**/*.js','src/js/child-theme-scripts.js'])
    .pipe(plumber({
      errorHandler: function (error) {
        console.log(error.message);
        this.emit('end');
    }}))
    .pipe(jshint())
    .pipe(jshint.reporter('default'))
    .pipe(concat('main.js'))
    .pipe(gulp.dest('dist/scripts/'))
    .pipe(rename({suffix: '.min'}))
    .pipe(uglify())
    .pipe(gulp.dest('dist/scripts/'))
    .pipe(browserSync.reload({stream:true}))
});
`

**Comment by nunospot** [comment]
Hello,

So I'm developing a theme with the understrap, but I'm not getting one thing on the js structure. Supposedly my customs js are in the src/js/theme-scripts and on the gulp script task I add the basePaths.dev + 'js/theme-scripts/*.js' so that all my scripts are concat to the theme.js.

Everything is fine. 

My question is, if I switch my dev computer, I need to install the understrap so I can have the dependencies there, but there is a postinstall task on the package.json that clean the src (gulp copy-assets). With this all my custom scripts are delete. 

So, am I missing anything? 

Thanks

**Comment by sommerset** [comment]
What I usually do is split the scripts task into 2 separarte tasks (Mostly  because I use a slow computer and re processing bootstrap's scripts  make no sense. )
Here is my modified version, keeping my own scripts on the scripts task and moving the libraries script's to a new task called lib-scripts.

**Comment by nunospot** [comment]
@sommerset, yeah it's a idea. I will give it a shot. Thank you.

**Comment by nunospot** [comment]
@sommerset, Hello again. 

Your idea was nice, but the problem remains. If you run the clean-source task that comes with the original gulpfile from understrap, all your src is delete.

**Comment by fahaddsheikh** [comment]
I have a weird problem. When i run ``gulp watch``  the css in _theme.scss gets compiled in theme.css but not in theme.min.css. Could someone tell me what could be causing this issue?

**Comment by blachawk** [comment]
I just want to say thank you  @holger1411 for making the process simple. I downloaded UnderStrap 0.8.8 and I'm currently using it as a starter theme.  I following your instructions in the comments to add a custom javascript file to my /src directory.  I then added my custom code to that file, stopped running **gulp watch-bs**, restarted **gulp watch-bs**, and now see my custom javascript on site.  

Thanks!
