### ISSUE TITLE
jQuery not loaded

### ISSUE THREAD

**Issue by Tom-Hayes** [holger1411/understrap#470]
Hi,

This could potentially be me being daft but for some reason jQuery doesn't seem to be loading in Understrap in WP 4.9... 

Cheers!

**Comment by LadikCZ** [comment]
Same for me... :(

**Comment by holger1411** [comment]
Its a problem with the Bootstrap 4 Beta 2 requirements for jQuery and WordPress.
The problem will be fixed with Beta 3
Till then pls use UnderStrap 0.6.5

**Comment by holger1411** [comment]
...or try the new 0.6.7
0.6.7 uses both jQuery version. The old one needed bei WP in noConflicht mode, and jQuery slim 3.2.1 for Bootstrap.
Its just a workaround, because it adds 23kb more weight to it and may generate some $ conflict bugs in your console (but it works...), but is a more solid solution than 0.6.6 till Bootstrap 4 Beta 3 comes out.

**Comment by antonapua** [comment]
Using understrap 6.10 jQuery is not loaded.

**Comment by holger1411** [comment]
*Should* be fixed now with 0.6.12

**Comment by Amn37ia** [comment]
Hi i've problem with jquery is seem not loaded,
im using understrap v.0.8.0
and i've following docs installation about node.js but seem, some of features of bootstrap that im using like : scrollspy,etc is not really working.

and yes jquery also is not happen to work.

**Comment by holger1411** [comment]
@Amn37ia Can you post a link? The theme itself did not load jQuery, but WordPress loads it on its own (...normally).

**Comment by brunomac** [comment]
same here. :(
wordpress 4.9.4;
understrap 0.8.0
understrap-child 0.5.0

**Comment by glur4k** [comment]
same for me.
wordpress 4.9.6;
understrap 0.8.2
