### ISSUE TITLE
Setting up the front page slider

### ISSUE THREAD

**Issue by mkoller** [holger1411/understrap#51]
I've done the following

- Click on Appearance → Widgets.
- Add two, or more, widgets of any kind to widget area “Hero”.
- That’s it.

Added some text boxes to the `hero slider` widget
<img width="733" alt="screen shot 2016-08-12 at 10 28 20 am" src="https://cloud.githubusercontent.com/assets/1036598/17627629/86969268-6077-11e6-82bc-e21225de3481.png">

Set a new page called home to the front page. 
<img width="204" alt="screen shot 2016-08-12 at 10 30 13 am" src="https://cloud.githubusercontent.com/assets/1036598/17627706/c7b27564-6077-11e6-81ce-1d49ed8211af.png">

But I'm not getting a slider on the front page, there are no console errors.
<img width="1142" alt="screen shot 2016-08-12 at 10 30 53 am" src="https://cloud.githubusercontent.com/assets/1036598/17627753/f5a4e394-6077-11e6-9d96-fda1140ce745.png">

`npm install` `bower install` `gulp copy-assets` and browserync all work flawlessly, anything I'm missing?

*Edit* do I manually have to add the slider to a page template?

     <div class="wrapper" id="wrapper-hero">
     <div class="owl-carousel">
     <?php dynamic_sidebar( 'hero' ); ?>
     </div>
    </div>

**Comment by holger1411** [comment]
Hi!
The problem in your case might by line 17 in index.php (https://github.com/holger1411/understrap/blob/master/index.php#L17), which looks like:

`  if ( is_front_page() && is_home() ) {`
It checks if it is the front page and the homepage.
The "is_front_page" checks if it is the blog page where all the articles will appear.
If you set a static page as homepage te slider will disappear, because it is still the homepage but not the front_page (in the WP terminology) anymore.
It was one of the coding standards requested by the WP Theme review team during the submission process for adding UnderStrap to the wordpress.org theme repository.

But you should be able to change it in your case just to:
if ( is_home() ){
Than the slider *should* appear even if the frontpage is a static page.

**Comment by 2pixels** [comment]
Hi, I have the same issue with the hero slider. 
The hero widget doesn't appear on my static homepage. 
Here is how you can fix it: 
Copy these lines to page.php to the same place as index.php
`<?php if ( is_front_page() ) : ?>
	<?php get_template_part( 'global-templates/hero' ); ?>
<?php endif; ?>`

**Comment by 2pixels** [comment]
Hi, I have the same issue with the hero slider. The hero widget doesn't appear on my static homepage. 
Here is how you can fix it: 
1. Copy these lines to page.php to the same place as index.php
`if ( is_front_page() && is_home() ) :
get_template_part( 'global-templates/hero' );
endif;
`

**Comment by brevelles** [comment]
For me the solution was to add `if ( is_front_page() )` to the page.php file.

**Comment by dewolfe001** [comment]
Wow. This works like a charm! I keep tripping over aspects of the my work where I say, "I'm going to have to do a lot of coding and configurations..." -- only to find it's already built into Understrap.
