### ISSUE TITLE
Struggling with sourcemaps

### ISSUE THREAD

**Issue by jakew009** [holger1411/understrap#52]
Hello

I've been tearing my hair out all day trying to get the CSS sourcemaps working.

I just can't get them to link back to the original files no matter what I do.

I just realised they don't seem to work on the demo here either: https://understrap.com/understrap/

Maybe they are working as intended, but I assumed that they should link back to the original files in Chrome Developer Tools, however all I see are line references to theme.min.css, which are obviously pretty useless.

Thanks for any help / insight!

EDIT:
After some more investigation I just noticed the code was added by @akkolad and I see he has actually made another pull request subsequent to his first one.
I can confirm that his new code does work :)

@akkolad could you confirm what commands you intended to run for both dev & production? I am a little confused looking at the code.

Jake

**Comment by akkolad** [comment]
Hi jake,
I use the watch-scss task in the dev environment, which is ideal because it's fast and the sourcemaps are Ok.
When you want to go to prod, run the scss-for-prod task, and you have to change the call of the .css file by the min.css file.

I just finished a project with understrap and except the problem with the sourcemaps everything was OK.

**Comment by holger1411** [comment]
Ah, sorry. Seems I just forgot to merge your last pull-request.
I also add gulp-clone and gulp-merge to package.json, so run "npm update"

Thx to @akkolad and @jakew009
