### ISSUE TITLE
Question more than an issue. Child theme custom bootstrap-wp-navwalker

### ISSUE THREAD

**Issue by TimHerbert** [holger1411/understrap#529]
First off I have to say I love your theme for a starting point for theme development. Great work! 

The theme I'm building needs to have a more customised navwalker to make it work the way the navigation needs to. 

All I've simply tried to do is move the /inc/boostrap-wp-navwalker.php file into the child theme and of course, it didn't work. So I ended up just modifying the parent theme which will get overwritten when we update. 

I am hoping you can point me in a simple direction to be able to move this functionality to the child theme.

Thanks in advance!

**Comment by crstnio** [comment]
Hey,

did you forget to include/require the class file in `functions.php`? Since this class is pluggable, it should work. Also, you should only copy the class, not the complete file. Without the `class_exists()` statement. Though, I don't know if the last is causing a conflict.

Additionally, you could extend this class, like it extends `Walker_Nav_Menu` itself. This has the advantage that you could choose which `wp_nav_menu()` will use the extended class by editing the `walker` argument.

**Comment by TimHerbert** [comment]
I'll try this when I get a chance. Thank you for your feedback!

**Comment by TimHerbert** [comment]
Looks like this works. I just renamed the included function I copied over and called it with the walker in the nav menu and worked like a charm.

**Comment by Portismouth** [comment]
@TimHerbert I'm having trouble making this work. I tried copying the inc folder and the class file in my child-theme, then changing the class name, including it in my functions.php and then calling it as the walker in the wp_nav_menu array... The site errors out saying that the class doesn't exist. Halp!

**Comment by pattonwebz** [comment]
@Portismouth Just to confirm you renamed the class INSIDE the file (not just renamed the file) and updated the include to point at the new file?

**Comment by TimHerbert** [comment]
@Portismouth It has been so long since I did this I don't even remember what project I did this for. Sorry man.

**Comment by Portismouth** [comment]
@TimHerbert no worries. Thanks for getting back to me, man.

@pattonwebz I copied the file, renamed it, removes the class_exists() check and renamed the class. In my child's functions.php, I updated the require statement to use get_stylesheet_directory() and append the path to the file - no luck so far.

All I really want to do is changed the behavior of nav links with children from 
`
if ( isset( $args->has_children ) && $args->has_children && 0 === $depth && $args->depth > 1 ) {
				$atts['href']          = '#';
				$atts['data-toggle']   = 'dropdown';
				$atts['aria-haspopup'] = 'true';
				$atts['aria-expanded'] = 'false';
				$atts['class']         = 'dropdown-toggle nav-link';
				$atts['id']            = 'menu-item-dropdown-' . $item->ID;
			}
`
to
`
if ( isset( $args->has_children ) && $args->has_children && 0 === $depth && $args->depth > 1 ) {
			$atts['href']          = $item->url;
			$atts['data-toggle']   = '';
			$atts['aria-haspopup'] = 'true';
			$atts['aria-expanded'] = 'false';
			$atts['class']         = 'dropdown-toggle nav-link';
			$atts['id']            = 'menu-item-dropdown-' . $item->ID;
		}
`
My client wants the dropdown to open on hover instead of click. A nudge in the right direction would be appreciated.

**Comment by Portismouth** [comment]
I figured it out. Thanks for the replies everyone.

**Comment by pattonwebz** [comment]
@portismouth glad you got it solved :)

If you could post a little info about how you got it working that would be real useful for the next person facing this request from their client.

**Comment by Portismouth** [comment]
Sure thing. See below. 

### The Problem
My client wanted a menu item with children to act as a link instead of activating the javascript that toggles the dropdown in bootstrap. 

### The Solution
By default, the navwalker class in the understrap theme sets the parent menu item's href attribute to "#", then sets its data-toggle attribute to 'dropdown' which has an event listener in bootstraps jQuery library. 
I didn't want to write any JavaScript to override that behavior because... JavaScript... so I altered the themes navwalker class to set the dropdown's parent element's attributes differently.

In order to remove the default behavior the dropdown menu, I:

- copied the _class-wp-bootstrap-navwalker.php_ file into the child theme I was using 
- appended _-child_ to the file name
- removed the class_exists() statement
- changed the class name to _Understrap_Child_WP_Bootstrap_Navwalker_
- altered the attr['href'] value to be set to the item's url set in Menus and had it set the data-toggle attribute to an empty string. 

Hopefully this helps someone else who gets a request to alter the default behavior of bootstraps nav.

@pattonwebz let me know if you want me to go into more detail.

**Comment by pattonwebz** [comment]
@portismouth that's absolutely perfect instructions for those in the future that need this. 

For a little context I get asked all the time to make the walker work with hover or to enable links on parent items. I chose many years ago not to add such features as I was keeping it following the core bootstrap ideals only. Still clients ask for the features and developers need to add them for the client. It is good to be able to send them to instructions on how to make it happen even though I have not put the features in the walker directly :)
