### ISSUE TITLE
reverse gulp

### ISSUE THREAD

**Issue by uitta** [holger1411/understrap#532]
I know this could sound.... silly and stupid but...
I made a website with understrap and everything is ok... i then erased everything local.
Then my client asked me for some other changes and when i downloaded everything i knew i made a huge mistake.... i uploaded only the css file generated by gulp but not the original sass files, which i lost erasing everything locally.
I know, i should use git and/or other version control but still.... i'm still learning....

Is there a way i could de-gulp the files to obtain the sass files?

thank you in advance.

Vitta

**Comment by ZacharyElkins** [comment]
IDK if someone has a better option, but as far as I know you'll be doing a lot of manual editing to recover your SASS.

1. Download fresh copy of the theme (same version as the website you're working on)
2. Copy over all edited files: functions, page templates, etc. (NO CSS)
3. Use [https://css2sass.herokuapp.com/](https://css2sass.herokuapp.com/) to convert your CSS file to SASS. This is where it will be tricky, as you have a lot of Bootstrap CSS in there. You could delete the bootstrap portion, which should be before your custom CSS.
4. Organize and check your SASS, put it in the theme, and test to find if anything is missing.

Good luck. And next time make sure to use GIT control. Sourcetree and Gitkraken are easy to use once you figure out how to set up a repo, there are plenty of Youtube guides to help. Also, you can use `gulp dist-product` to output the theme with the SASS files, so that your projects keep the original SASS just it case.
