### ISSUE TITLE
Understrap too wide on MacBook Pro Safari and Chrome

### ISSUE THREAD

**Issue by paulstonee** [holger1411/understrap#566]
Hi there! I'm completely new to both wordpress and bootstrap but I decided to try and customize a theme to my needs with understrap. Everything seemed to go rather smoothly until the point where I discovered that website width is just too wide. It make the bottom horizontal scroll bar appear which I was trying to avoid all the time. This only appears in fullscreen with Safari and Chrome on my MacBook Pro. It does not happen with mobile devices or other browsers on PC running on Windows that I checked. Can anyone help me find the bug here ? 

Here's a screen showing the problem:

https://www.dropbox.com/s/xuutvermhqyvfoq/Zrzut%20ekranu%202018-02-23%2016.52.10.png?dl=0

Thanks in advance, 
Paul

**Comment by axlright** [comment]
@paulstonee That's an issue I see come up from time to time - it's not an issue with Understrap or Boostrap. It's usually caused by something in your markup being set to a padding that is causing a conflict. That right space you're seeing is 15px of padding or negative margin based on not properly setting everything up.

I'd go through your markup from top to bottom and make sure that any column is in a row is in a container and that no columns are set to 0 padding.

You'll find it eventually and probably kick yourself. At least that's what happens to me.

**Comment by paulstonee** [comment]
You were right @axlright . Thanks for your help :). I found it was .wrapper{ padding: 0px 0px;} making the problem. It's set to 30px top padding by default. Still, I would like to get rid of that padding since I don't want these empty spaces on top and bottom. Now I'm confused and I have no idea how to achieve that without causing the conflict by setting it to 0. Is there another way ?

https://www.dropbox.com/s/h48l8eby68ivjz5/Zrzut%20ekranu%202018-02-23%2018.52.58.png?dl=0

https://www.dropbox.com/s/h47y160ket78jr3/Zrzut%20ekranu%202018-02-23%2018.53.05.png?dl=0

Any response will be much appreciated,
Thanks,
Paul

**Comment by axlright** [comment]
@paulstonee The top and bottom padding should have no impact but the left and right will. I'd just play around until you get it right.

**Comment by paulstonee** [comment]
I found it ! It turned out it was my fault setting Row stretch within row settings to "Stretch row and content (no paddings)" instead of just leaving it "deafult". Once I had put it back to default it solved the problem. Thanks for your help @axlright . 👍 

https://www.dropbox.com/s/nk3jvn33sreyinq/Zrzut%20ekranu%202018-02-23%2019.33.56.png?dl=0
