### ISSUE TITLE
Extra sidebar below Woocommerce product page

### ISSUE THREAD

**Issue by holger1411** [holger1411/understrap#733]
## Issue is about..
  - [x ] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 4.9.6
  - **WooCommerce Version:** 3.4.3

---

# Issue Overview for Bugreports
A sidebar is rendered below the main wrapper on product overview and single product view: https://understrap.com/understrap/?post_type=product

## Steps to reproduce?
Open https://understrap.com/understrap/?post_type=product

## *Who* is the bug affecting?
Any WooCommerce user

## Screenshots / Video
![screenshot-understrap com-2018-07-03-09-23-47](https://user-images.githubusercontent.com/1568158/42204761-dda9045a-7ea2-11e8-86ce-fb6ef160dbef.png)

## Expected behavior
No extra full width sidebar below the main wrapper

Maybe related to @ZacharyElkins changes (?)

**Comment by ZacharyElkins** [comment]
Wow. I'm perplexed with this one.

I'll look into it. Really strange as it is placed outside of the WooCommerce wrapper.

**Comment by holger1411** [comment]
The strang thing is that this sidebar starts with:
`<div id="sidebar" role="complementary">`

which isnt part of understrap. Seems to be the default WP sidebar

**Comment by gaelgerard** [comment]
Hello all,

Since I updated understrap a few minutes ago on my local website, this strange Sidebar is appearing on Every page. No woocommerce in use.

I will tell you if I find a solution.

Best regards,

gael

**Comment by noelspringer** [comment]
Hi, I just installed a fresh copy of WordPress with UnderStrap 0.83 and Woocommerce populated with dummy data.

I also have php errors turned on. The extra sidebar **does** show up. It contains:

* Search
* Pages
* Archives
* Categories

The following PHP error appears under the pagination and above the Search bar:

> Notice: Theme without sidebar.php is deprecated since version 3.0.0 with no alternative available. Please include a sidebar.php template in your theme. in /path/to/wp-includes/functions.php on line 3984

You may recall that when the sidebar templates were moved to the `sidebar-templates` directory that the `sidebar.php` file was dropped since it wasn't being used anywhere.

Adding back the `sidebar.php` file from version 0.8.2 fixes the problem.

**Comment by webstylr** [comment]
I confirm noels solution:
did the same he (fresh install, etc), got the error.
added sidebar.php to the theme root => error gone.

**Comment by axlright** [comment]
This is partially on me - apologies. I moved the sidebar files into a dedicated sidebar directory and deleted the root sidebar.php

>Notice: Theme without sidebar.php is deprecated since version 3.0.0 with no alternative available. Please include a sidebar.php template in your theme.

I wasn't aware of this and didn't do enough research. I was under the assumption that WordPress themes _technically_ only needed a style.css, index.php, comments.php and screenshot.png. If a blank sidebar.php is required, I can add it since I'm the one who issued the PR that deleted the original.

**Comment by bc1974A** [comment]
I confirm the above, I didn't need to delete parent or child theme, but to change my child to match the parent sidebar calls (eg `<?php get_template_part( 'sidebar-templates/sidebar', 'footerfull' ); ?>`).

Then, Woocommerce was my only remaining issue and adding a blank sidebar.php in the child theme worked.

Perhaps some instead of that, if that's not the desired solution, is to work with the `'woocommerce_sidebar'` action?

**Comment by ZacharyElkins** [comment]
@bc1974A

The wrapper function in inc/woocommerce.php will need the updated path to the sidebars. That should be it. Sorry, on mobile and can’t provide code.

**Comment by holger1411** [comment]
Okay, can confirm this: After adding an empty sidebar.php file into root the additional sidebar on woocommerce pages is gone.

**Comment by bc1974A** [comment]
Sorry I know its closed, but just following up that I needed a blank sidebar in the child theme also, otherwise woocommerce outputs the same issue
